### ISSUE TITLE
"Find another match" button not working as expected

### ISSUE THREAD

**Issue by ngzhenteng** [CS3219-AY2223S1/cs3219-project-ay2223s1-g27#107]
After timer times out after 30s, "Find another match" button redirects to landing page instead of countdown timer

**Comment by github-amanda** [comment]
Sorry, are you able to provide a screenshot? Currently, we only have "Wait for another 30 seconds" and "Select another difficulty level" buttons. "Wait for another 30 seconds" resets the timer, while "Select another difficulty level" will redirect you to back to the landing page.
