### ISSUE TITLE
Deployment Website tab does not include our logo

### ISSUE THREAD

**Issue by ngzhenteng** [CS3219-AY2223S1/cs3219-project-ay2223s1-g27#119]

**Comment by ngchisern** [comment]
I can see it on my end. 

<img width="370" alt="Screenshot 2022-11-05 at 11 43 33 PM" src="https://user-images.githubusercontent.com/64767959/200128120-ea37d522-60ae-4653-acd6-d579676e604c.png">

**Comment by ngzhenteng** [comment]
Ok! probably an error with my chrome caching, thanks
